version: "3.8"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_benchmarking
    ports:
      - "8000:8000"
    environment:
      - "UV_THREADPOOL_SIZE=6"
